repos:
  # General code formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^tsconfig.*\.json$
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending

  # TypeScript/JavaScript frontend checks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        files: ^src/.*\.(ts|tsx|js|jsx)$
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - 'eslint-plugin-react'
          - 'eslint-plugin-react-hooks'

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Check
        entry: bash -c 'npm run typecheck'
        language: system
        files: ^src/.*\.(ts|tsx)$
        pass_filenames: false

  # Prettier for frontend code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: ^src/.*\.(ts|tsx|js|jsx|css|json|md)$
        additional_dependencies:
          - 'prettier@^3.0.0'

  # Optional: Run frontend tests
  #- repo: local
  #  hooks:
  #    - id: frontend-tests
  #      name: Frontend Tests
  #      entry: bash -c 'cd frontend && npm run test:run'
  #      language: system
  #      files: ^src/.*\.(ts|tsx)$
  #      pass_filenames: false
