# Generated by Django 5.2 on 2025-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='submitted_key',
            field=models.BigIntegerField(),
        ),
    ]
