# Generated by Django 5.2 on 2025-05-16 01:08

from django.db import migrations

INITIAL_CHALLENGES = (
    (
        "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        "04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f",
        "https://www.blockchain.com/explorer/addresses/BTC/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        ("SATOSHI", "MINED", "ORIGIN", "BLOCK:0"),
    ),
    (
        "12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S",
        "0411db93e1dcdb8a016b49840f8c53bc1eb68a382e97b1482ecad7b148a6909a5cb2e0eaddfb84ccf9744464f82e160bfa9b8b64f9d4c03f999b8643f656b412a3",
        "https://www.blockchain.com/explorer/addresses/BTC/12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S",
        ("SATOSHI", "MINED", "ORIGIN", "BLOCK:9", "FIRST TRANSACTION SENDER"),
    ),
)


def create_challenges(apps, schema_editor):
    """
    Create a bunch of initial challenges
    """
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ChallengeSentinel = apps.get_model("game", "ChallengeSentinel")
    Challenge = apps.get_model("game", "Challenge")
    Metadata = apps.get_model("game", "Metadata")
    if not ChallengeSentinel.objects.exists():
        ChallengeSentinel.objects.create()
    for challenge in INITIAL_CHALLENGES:
        addr, pubkey, explorer, tags = challenge
        c = Challenge.objects.create(
            p2pkh_address=addr, public_key=pubkey, explorer_link=explorer
        )
        c.save()
        for tag in tags:
            metadata = Metadata.objects.create(name=tag, challenge=c)
            metadata.save()


def remove_challenges(apps, schema_editor):
    """
    Reverse create challenges
    """
    ChallengeSentinel = apps.get_model("game", "ChallengeSentinel")
    Challenge = apps.get_model("game", "Challenge")
    addrs = [c[0] for c in INITIAL_CHALLENGES]
    ChallengeSentinel.objects.delete()
    for challenge in Challenge.objects.all():
        if challenge.p2pkh_address in addrs:
            challenge.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_challenges, remove_challenges)]
