# Generated by Django 5.2 on 2025-05-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_guess_submitted_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='submitted_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_key', to='game.publickey', to_field='private_key'),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='private_key',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='x',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='y',
            field=models.BigIntegerField(),
        ),
    ]
