# Generated by Django 5.2 on 2025-06-06 15:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_save"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_key", models.CharField(max_length=66)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("negated", "Negated"),
                        ],
                        null=True,
                    ),
                ),
                ("signature", models.CharField(max_length=128)),
                ("is_signature_valid", models.BooleanField(blank=True, null=True)),
                ("is_key_valid", models.BooleanField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="game.challenge",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Guess",
        ),
    ]
